- name: Change the NewAdministratorName
  win_security_policy:
    section: System Access
    key: NewAdministratorName
    value: "_winadmin_"

- name: Change the NewGuestName
  win_security_policy:
    section: System Access
    key: NewGuestName
    value: "_winguest_"

- name:  Change the ClearTextPassword
  win_security_policy:
    section: System Access
    key: ClearTextPassword
    value: 0

- name: Change the LSAAnonymousNameLookup
  win_security_policy:
    section: System Access
    key: LSAAnonymousNameLookup
    value: 0
  
- name: Change the EnableAdminAccount
  win_security_policy:
    section: System Access
    key: EnableAdminAccount
    value: 1 

- name: Change the EnableGuestAccount
  win_security_policy:
    section: System Access
    key: EnableGuestAccount
    value: 0 